### ISSUE TITLE
Edit plot_javascript function so that it displays the correct image if you switch attention heads

### ISSUE THREAD

**Issue by soniajoseph** [soniajoseph/ViT-Prisma#52]

**Comment by soniajoseph** [comment]
![Screen Shot 2024-01-13 at 8 34 55 PM](https://github.com/soniajoseph/ViT-Prisma/assets/29527088/cb9382db-2391-401e-a060-277d9c3ca7e4)
![Screen Shot 2024-01-13 at 8 35 12 PM](https://github.com/soniajoseph/ViT-Prisma/assets/29527088/17347b5e-3dc7-437a-a59e-4e8e829563e4)

Image between 1 and 2 remains the same even though the datapoints are different

**Comment by soniajoseph** [comment]
Tagging you @themachinefan but zero pressure! It was already great work :)

**Comment by themachinefan** [comment]
No problem, I should be able to do it

**Comment by soniajoseph** [comment]
Looks great and works on [attn head notebook](
https://colab.research.google.com/drive/1xyNa2ghlALC7SejHNJYmAHc9wBYWUhZJ#scrollTo=LyT5dHHznE-c)
