### ISSUE TITLE
Adapt CLIP suite to HookedViT

### ISSUE THREAD

**Issue by soniajoseph** [soniajoseph/ViT-Prisma#81]
- [ ] CLIP small
- [ ] CLIP medium
- [ ] CLIP large

**Comment by clemneo** [comment]
@themachinefan is the CLIP suite supported yet?

**Comment by themachinefan** [comment]
Should be, I think the issue can be closed

**Comment by soniajoseph** [comment]
Feel free to reopen the issue if this is not the case!
